// This file is generated by Astro DB
declare module 'astro:db' {
	export const users: import("@astrojs/db/runtime").Table<
		"users",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"users","primaryKey":true}},"fullName":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"fullName","collection":"users","primaryKey":false,"optional":false}},"password":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"password","collection":"users","primaryKey":false,"optional":false}},"email":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"email","collection":"users","primaryKey":false,"optional":false}},"createdAt":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"createdAt","collection":"users","default":{"__serializedSQL":true,"sql":"CURRENT_TIMESTAMP"}}},"updatedAt":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"updatedAt","collection":"users","default":{"__serializedSQL":true,"sql":"CURRENT_TIMESTAMP"}}}}
	>;
}
